@php
    echo'<?xml version="1.0" encoding="UTF-8"?>';
@endphp
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">   
    <url>
        <loc>https://www.dokterlegal.co.id/</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/home</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/about-us</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/layanan</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/layanan/pendirian-perusahaan</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/layanan/pendirian-pt</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/layanan/pendirian-pt-persekutuan-modal</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/layanan/pendirian-pt-perorangan</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/layanan/pendirian-cv</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/layanan/pendirian-firma</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/layanan/pendirian-persekutuan-perdata</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/layanan/penanaman-modal-asing</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/layanan/pendirian-yayasan</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/layanan/pendirian-koperasi</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/layanan/pendirian-perkumpulan</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/layanan/penutupan-perusahaan</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/layanan/virtual-office</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/layanan/virtual-office-one-page</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/layanan/perizinan-khusus</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/layanan/digital-marketing</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/layanan/perizinan-usaha</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/layanan/perpajakan</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/layanan/haki</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/layanan/hukum</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/layanan/perizinan-properti</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/layanan/privilege</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/layanan/pembuatan-perjanjian</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/layanan/pembuatan-dokumen</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/layanan/layanan-lainnya</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/layanan/idak</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/layanan/ppiu</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/faq</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/contact</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/kbli-terbaru</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/cek-nama-pt</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/tracking-system</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/e-book</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/career</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/promo</loc>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://www.dokterlegal.co.id/artikel</loc>
        <priority>1.00</priority>
    </url>
    @foreach($getCareer as $itemsCareer)
        <url>
            <loc>https://www.dokterlegal.co.id/career/{{ $itemsCareer->career_slug }}</loc>
            <lastmod>{{ gmdate(DateTime::W3C, strtotime($itemsCareer->updated_at)) }}</lastmod>
            <priority>1.00</priority>
        </url>
    @endforeach

    @foreach($getPromo as $itemsPromo)
        <url>
            <loc>https://www.dokterlegal.co.id/promo/{{ $itemsPromo->promo_slug }}</loc>
            <lastmod>{{ gmdate(DateTime::W3C, strtotime($itemsPromo->updated_at)) }}</lastmod>
            <priority>1.00</priority>
        </url>
    @endforeach

    @foreach($getArtikel as $itemsArtikel)
        <url>
            <loc>https://www.dokterlegal.co.id/artikel/{{ $itemsArtikel->artikel_slug }}</loc>
            <lastmod>{{ gmdate(DateTime::W3C, strtotime($itemsArtikel->updated_at)) }}</lastmod>
            <priority>1.00</priority>
        </url>
    @endforeach
</urlset>
